# CoCon Vote Monitor
# environment.yml
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 3P Technologies Srl
# Author: Marco Miano

# Environment file to create a conda environment for the project
name: cocon_vote_monitor
channels:
  - defaults
dependencies:
  - python=3.13
  - aiohttp
  - pip
  - pip:
      - uvicorn[standard]
      - starlette
      - cocon_client
