name: Release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
        inputs:
            version:
                description: "Version string to use when manually running (e.g., v.1.2.3dev)"
                required: false
                default: 'dev'

permissions:
    contents: write

env:
    VERSION: ${{ github.event.inputs.version || github.ref_name }}

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up micromamba
            uses: mamba-org/setup-micromamba@v2
            with:
                micromamba-version: '2.3.2-0'
                cache-environment: true
                environment-file: environment.yml
                create-args: >-
                    -n cocon_vote_monitor
          
          - name: Install conda-pack
            shell: bash -l {0}
            run: micromamba install -y -n base conda-pack
        
          - name: Pack environment
            id: pack
            shell: bash -l {0}
            run: |
              PLATFORM="$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)"
              BASENAME="cocon_vote_monitor_${VERSION}_${PLATFORM}"
              STAGING_ROOT="$(mktemp -d)"
              STAGE="${STAGING_ROOT}/${BASENAME}"
              mkdir -p "${STAGE}/src"

              # Create env tarball
              micromamba run -n base conda-pack -p "${MAMBA_ROOT_PREFIX}/envs/cocon_vote_monitor" \
                                                -o env.tar.gz

              # Stage files
              mv env.tar.gz "$STAGE/"
              # include your source tree
              rsync -a --exclude '.git' --exclude '.github' \
                       --exclude '__pycache__' --exclude '*.pyc' \
                       --exclude 'env' --exclude '*.tar.gz' \
                       "${GITHUB_WORKSPACE}"/ "${STAGE}/src/"
              
              # Minimal INSTALL
              cat > "${STAGE}/INSTALL.md" <<'EOF'
              # Quick start
              mkdir ./env
              tar -xzf env.tar.gz -C ./env
              ./env/bin/conda-unpack
              cd src
              # Edit ./src/cocon_vote_monitor/config.py or other files and run.
              ../app_env/bin/python -m uvicorn cocon_vote_monitor.app:app --reload
              EOF

              tar -C "${STAGING_ROOT}" -czf "${BASENAME}.tar.gz" "${BASENAME}"
              mv "${BASENAME}.tar.gz" "${GITHUB_WORKSPACE}/"
              echo "archive=${BASENAME}.tar.gz" >> "${GITHUB_OUTPUT}"
          
          - name: Publish release
            uses: softprops/action-gh-release@v2
            with:
                tag_name: ${{ github.event.inputs.version || github.ref_name }}
                name: ${{ github.ref_name }}
                files: ${{ steps.pack.outputs.archive }}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}